# Generated by Django 5.1.7 on 2025-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_certificate_certificate_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('applicant_name', models.CharField(max_length=255)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('resume_file', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
